import Footer from "@/components/footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";
import { ThirdwebProvider } from "@/app/thirdweb";

const syne = Syne({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syne.className}`}>
        <div className="bg-slate-900">
          <ThirdwebProvider>
            <Navbar />
            {children}
            <Footer />
          </ThirdwebProvider>
        </div>
      </body>
    </html>
  );
}
