import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { ThirdwebProvider } from "thirdweb/react";
import Footer from "@/components/footer/Footer";
import { VARIANT } from "../../lib/constants";
import "./custom-light.css";
import "./custom-dark.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const colorMode = "dark";
  return (
    <html lang="en">
      <body className={`${inter.className} ${VARIANT}-${colorMode}-bg`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
